### ISSUE TITLE
Security Unsecured path

### ISSUE THREAD

**Issue by Augustyn** [darkonion/DealFlowBus#5]
It's good that you think about security and try to avoid Path Traversal attack. Great, but not enough. What if someone will pass path '_/etc/passwd_', or starting with '_c:\\windows\\system\\_' ?

You may get application absolute path (preferably store in cfg?) and match it against incoming path, after changing it to `absoluthPath`

ref: https://github.com/darkonion/DealFlowBus/blob/f08d0840ec166b0e95567f75b5a7ed2818800bc8/database-main-reader/src/main/java/com/dealflowbus/databasemainreader/services/DBFileService.java#L42

**Comment by darkonion** [comment]
Hmm, actually this line of code is useless since i decided, that all my files will be stored in mysql database as byte[]. As far as i am concerned, I am not threatened by path traversal attack here, because it is not an access point to my file system, but only to database through JPA Repository interface. 

If i am wrong, please explain why, maybe i am missing something.

**Comment by Augustyn** [comment]
ok, I guess
